### ISSUE TITLE
Cannot resume where I left off

### ISSUE THREAD

**Issue by pointyointment** [HackerPoet/MarbleMarcher#13]
I downloaded the Windows binary and started playing it. It worked fine, though I could only play it at potato quality. I got to the level "The Sponge", tried a few times, and exited to look at the levels, to see how far through the game I was. On trying to resume playing, I could not. I cannot get back into that level from the levels menu, because it's listed as "???". If I click on the level before it, I can play that level, but when I finish that level, it restarts that same level rather than going to the next one (the one I wanted to play). If I click "Play" in the main menu, it starts me at level 1.

**Expected behavior:**

* Clicking "Play" in the main menu starts me at the lowest-numbered level I haven't completed.
* The levels menu allows access to levels up to and including the lowest-numbered level I haven't completed.
* After completing a level chosen from the levels menu, I then get the next level.

**Observed behavior:**

* Clicking "Play" in the main menu starts me at level 1, regardless of what levels I've completed.
* The levels menu allows access to levels up to, but not including, the lowest-numbered level I haven't completed.
* After completing a level chosen from the levels menu, I can only play that same level again, until I exit to the menu.

**Comment by HackerPoet** [comment]
The levels menu always restarts the same level as it's convenient for speed-running/practicing.  I may even add a ghost feature.  So I don't really want to change that behavior.

How about having play resume the last locked level, or start from the beginning if you've already unlocked everything?  I will also fix the bug that the latest unbeaten level should still be available from the levels menu.

**Comment by HackerPoet** [comment]
Feature has been added.
