### ISSUE TITLE
Add mute music button

### ISSUE THREAD

**Issue by Contramalgra** [HackerPoet/MarbleMarcher#14]
As a player,
I want to control the music volume,
So I can play my own music but keep the game's SFX.

**Comment by HackerPoet** [comment]
Yes, if you've installed CMake, just set `CMAKE_MODULE_PATH` to a list of paths where the packages are located.

I will probably add the feature this weekend though.

**Comment by HackerPoet** [comment]
Feature has been added.  If you're still having the CMake problem, you can open another issue.
