### ISSUE TITLE
No video settings.

### ISSUE THREAD

**Issue by coolmax10** [HackerPoet/MarbleMarcher#21]
There are no video settings. I want to play in high res without the graphical effects. I have 12 frames on 1920 x 1080 or I have blurry pixals on 640 x 360.
Graphics Card: NVIDIA GeForce 940MX

**Comment by HackerPoet** [comment]
The only effect that has any significant impact on performance is shadows, but I feel the game is too ugly without them, and actually a bit harder to play when you can't judge the marble height as easily.  You can hack the graphical settings lower if you want by modifying assets/frag.glsl (look at the defines at the beginning)

**Comment by coolmax10** [comment]
ok
