### ISSUE TITLE
Add fractal viewer mode

### ISSUE THREAD

**Issue by GithubSuckBigTime** [HackerPoet/MarbleMarcher#23]
This is a feature request that I think would be both very useful and relatively simple to implement.

There could be a free view mode in which 3D fractals could be explored. It might be similar to the screensaver mode (could potentially replace it), just with the ability to move the camera and change the fractal parameters.

Even if very simple, this would make for a nice tool to complement programs such as Mandelbulber, which is not real-time.

Let me end by a thank you for this great project.

**Comment by HackerPoet** [comment]
I may add a 'cheats' menu at some point, which can include noclip to explore.

**Comment by HackerPoet** [comment]
Free camera has been added in the latest update.
