### ISSUE TITLE
Clarify asset license

### ISSUE THREAD

**Issue by GithubSuckBigTime** [HackerPoet/MarbleMarcher#24]
Could the usage rights of the assets please be clarified? I can see there is a font license, but none for the sounds and music. This is important e.g. for the ability to be included in some package repositories.

**Comment by HackerPoet** [comment]
They're intended to also fall under the GPL licence.  Or can that not apply for assets?

**Comment by GithubSuckBigTime** [comment]
Games typically license assets with Creative Commons -- GPL can apply to assets as well but in this case it is better to explicitly state this, e.g. in README or COPYING, because the GPL is intended for code and there can be confusion whether the author really mean to apply it to the assets as well.

The statement in your comment here is probably enough and can be referenced to make this clear, but for better visibility it would be better to include this somewhere in the repository as well.

**Comment by HackerPoet** [comment]
I've added a Creative Commons Share Alike license.
