### ISSUE TITLE
GPL3 issues

### ISSUE THREAD

**Issue by kungfooman** [HackerPoet/MarbleMarcher#3]
Hey, thank a alot for releasing this, this looks super useful and interesting to learn from. I work with some other game engines which happen to be GPL2 (OpenJK and other Raven/idtech3 engine spinoffs). The problem now is that it's not legal to mix GPL3 with GPL2 source code. That would require the GPL2+ license for those other game engines.

Could you please use a more liberal license, like ISC/BSD/MIT? Then this code can be used in a lot more projects.

**Comment by HackerPoet** [comment]
Would changing to GPL2+ be sufficient for your needs?  The main reason I'm using GLP is just to make sure someone isn't simply repackaging the game and selling it.  Normally I'd use a more permissive licence if it was just a smaller demo or library that has less immediate commercial value.

Also as the author and holder of the copyright (copyleft?).  I may be able to simply grant exceptions, so as long as you're developing a different game, you can use the same engine and tech.

**Comment by kungfooman** [comment]
If you wanna stick to GPL, the best would be GPL2+ as far as I know. Then GPL2 and GPL3 (with and without +) projects have no problems. But this isn't a commercial protection, it simply means that the seller has to hand out the source code to anybody who asks for it.

Now I also work with glPortal (zlib license) and PlayCanvas (MIT license) and I would really love to see this working via WebGL and becomes adopted by multiple gamedev communities. There are so many possibilities like using the gyroscope sensor for movement on smartphones or Virtual Reality headsets.

If the license of MarbleMarcher would be compatible with all those engines it would allow maximum reusability in all kinds of game engines.

Yea, granting exceptions works as well, you could even make some money with that. ^^

**Comment by HackerPoet** [comment]
Licence has been updated to GPL2+ now.
