### ISSUE TITLE
Trouble in making CMakeLists.txt

### ISSUE THREAD

**Issue by sharshith** [HackerPoet/MarbleMarcher#31]
Hi bros,  by this game I was actually inspired to create my own game(or atleast to draw a picture on a window rather than printing text on a console). I installed(built from sources) the SFML and eigen dependencies the game ran fine and also good game btw :-). 

But the problem started when I tried to create my own CMakeLists.txt file. I read the documentation from SFML website and it is not given for Linux(where there is no graphical interface and everything has to be typed).So, I tried changing your CMakeList file and but you 2 CMakeLists.txt file(1 which is located in the projects folder and another in src folder) but it was just a failure. 

My main problem is I'm struggling to learn how to use CMake and I'm not understanding their doumentation and how to use it for adding SFML dependency.

I'm not doing any  type a big project or anything. I just want the code in https://www.sfml-dev.org/tutorials/2.5/start-linux.php in this to run.

Pls anyone help me with the CMakeList.txt. If possible please explain in detail what is happening in CMakeList.txt.
 May God bless anyone who read this fully.

And please help me. This is the only thing which is keeping me from moving forward

**Comment by MichaelMoroz** [comment]
Since the original CMakeLists.txt didn't work for me, it couldn't find the the SFML directory, I did some changes, and added the directory explicitly:

```

set(SFML_DIR SFML-2.5.1/lib/cmake/SFML)
set(SFML_LIB_DIR ../SFML-2.5.1/lib)
set(SFML_STATIC_LIBRARIES TRUE)
find_package(SFML 2.5 COMPONENTS system window graphics audio REQUIRED)
set(SFML_INCLUDE_DIR SFML-2.5.1/include)

```
and here
```
target_compile_definitions(PROJECT PRIVATE SFML_STATIC)
target_link_libraries(PROJECT 
  PROJECT_SOURCES
  sfml-system
  sfml-window
  sfml-graphics
  sfml-audio
  ${SFML_LIB_DIR}/freetype
  winmm
  gdi32
)
```
Hope it will help you

**Comment by sharshith** [comment]
Thanks but it is throwing some error
it is showing:
`CMake Error at /usr/local/lib/cmake/SFML/SFMLConfig.cmake:139 (message):
  Requested SFML configuration (Static) was not found
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)


CMake Error at CMakeLists.txt:8 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/SFML/SFMLConfig.cmake

  but it set SFML_FOUND to FALSE so package "SFML" is considered to be NOT
  FOUND.
`
I'm sorry but I didn't understand this part 
`target_compile_definitions(PROJECT PRIVATE SFML_STATIC)
target_link_libraries(PROJECT 
  PROJECT_SOURCES
  sfml-system
  sfml-window
  sfml-graphics
  sfml-audio
  ${SFML_LIB_DIR}/freetype
  winmm
  gdi32
)`

what is SFML_STATIC and PRIVATE ? and such part
Please if u have any other sources if info about this share it, so, that I can understand this stuff and figure out what to do.

**Comment by MichaelMoroz** [comment]
SFML_STATIC defines what librarys to use, if enabled SFML will link the
"*-s.lib" librarys and the executable will be compiled with them inside of
it.
It seems that your SFML version does not have the needed  "*-s.lib".
Though, I'm not sure about the exact reasons.

**Comment by sharshith** [comment]
I was successfully able to compile and run the MarbleMarcher game. But this example program(https://www.sfml-dev.org/tutorials/2.5/start-linux.php) made me to write my own cmakelists.txt where I don't know what to write to make it work. In cmake website also they use GUI for windows. but that is too much to ask for Linux and here I have to write it all. I mean I'm complaining to write  all on my own. I'm happy to learn btw. What frustrates me is I don't find the documentation required and desperately do a copy paste from stackoverflow and I get an error which I don't know what to do and revert back. This kind of problems are also specific since these kind of apis are used for specific purposes. Anyway thanks bro for helping me bro. I hope I can solve this and finally move on.

**Comment by sharshith** [comment]
Yes!, it finally WORKED.. Thanks for the help
