### ISSUE TITLE
[macOS Mojave 10.14.2] Fails to capture mouse

### ISSUE THREAD

**Issue by qwerasd205** [HackerPoet/MarbleMarcher#33]
On macOS, I compiled and ran it and it failed to capture the mouse when in gameplay, which causes the game to be unplayable as unless I blindly manage to center the mouse the camera flies all over the place.

**Comment by BryceAS202313** [comment]
I managed to figure this one out as I was compiling some prebuilt macOS binaries for Mr. Bullet. Here is what you have to do go to System Preferences > Security & Privacy > Privacy > Accessibility and put a checkmark next to MarbleMarcher or if it is not there, press plus and add it. By the way, if you want a nice `.app` bundle, here is the one I made: https://thenetworknerds.ca/marblemarcher/MarbleMarcher.dmg

**Comment by qwerasd205** [comment]
Ah, I see, it should be able to capture the mouse without that, as many games do, but that works as a work-around. Thanks for the info.
