### ISSUE TITLE
Further reading?

### ISSUE THREAD

**Issue by caleb-allen** [HackerPoet/MarbleMarcher#8]
Sorry if this is the wrong place, but I'm looking to get more info on this. 

I love this approach, it seems really novel, and I can't find anything similar to it. What is the potential of this to non-spherical object interaction? Pardon my ignorance on the mathematics. Any other sources or reading you could point me to that inspired this? This is super cool.

**Comment by HackerPoet** [comment]
It's novel and I haven't seen any other reading about this.  You may be interested in [PySpace](https://github.com/HackerPoet/PySpace). It has all the math more generally and with some documentation, compared to everything hard-coded in Marble Marcher.

For just the rendering part, [this tutorial](http://blog.hvidtfeldts.net/index.php/2011/06/distance-estimated-3d-fractals-part-i/) is a great resource.

A non-spherical object like a plane may be possible using this technique, but I'm not sure if the math works out to make that efficient.  Generally, I'd just construct your object as a collections of spheres and collide with that.

**Comment by caleb-allen** [comment]
Thanks for the links. Very interesting! Down the rabbit hole I go..

It will be interesting to see if this goes anywhere. A quick search reveals some [work at Purdue](https://pdfs.semanticscholar.org/33eb/d165fc664461599a483d7ddb7f295a76a128.pdf) of developing fractals for general purpose modeling. Whether it will be practical or not, the results are strangely beautiful:

![screenshot from 2019-01-09 15-35-27](https://user-images.githubusercontent.com/3279748/50933965-75d85200-1424-11e9-8a50-f626875fce38.png)

**Comment by caleb-allen** [comment]
Sorry for the multiple comments but this stuff is so fascinating! The same author Tim McGraw published [a paper](https://doi.org/10.1145/3230744.3230748) in October '18, applying concepts from volume rendering techniques used in medical image visualization to raycasting and fractals. The results are gorgeous:

![screenshot from 2019-01-09 16-01-32](https://user-images.githubusercontent.com/3279748/50935057-f6e51880-1427-11e9-8b6a-eb5c5b5f11ec.png)

**Comment by HackerPoet** [comment]
Closing since there is no open issue.
